chore: migrate to flat config
discordjs-japan/om pull request #303
Opened 2024-04-13 00:38 UTC by cm-ayf

2024-04-13 02:27 UTC, Mogyuchi requested changes

2024-04-13 07:14 UTC, Mogyuchi commented on eslint.config.js
> +  { files: ["**/*.js"], ...tseslint.configs.disableTypeChecked },
@cm-ayf 
Definitely Typed の出番です。

2024-04-13 07:16 UTC, cm-ayf commented on eslint.config.js
> +  { files: ["**/*.js"], ...tseslint.configs.disableTypeChecked },
なんと！　eslint-plugin-importには@typesがない！！

2024-04-13 07:17 UTC, Mogyuchi commented on eslint.config.js
> +  { files: ["**/*.js"], ...tseslint.configs.disableTypeChecked },
なんだって〜！😭

2024-04-14 03:35 UTC, Mogyuchi approved these changes

2024-04-14 03:37 UTC, merged