Add dotenv
discordjs-japan/om pull request #6
Opened 2023-10-20 23:00 UTC by femshima

Depends on: #5

2023-10-21 11:27 UTC, cm-ayf commented
#5 merged

2023-10-22 00:26 UTC, mouse484 requested changes
node 20系のLTSが10月24日から始まるのでnodeバージョンを20にして組み込みの.env使いませんか？

https://nodejs.org/ja/blog/release/v20.6.0#built-in-env-file-support

2023-10-22 12:02 UTC, femshima commented
現時点で@discordjs/opusがNode 20に対応していないため，残念ながら当面は18を使うことになります．

2023-10-24 06:20 UTC, mouse484 approved these changes

2023-10-27 04:21 UTC, merged